[2025-04-04T22:07:41.203+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-04-04T22:07:41.399+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: scrape_amazon_dag.process_Interior_Accessories_3 manual__2025-04-04T22:06:59.454233+00:00 [queued]>
[2025-04-04T22:07:41.532+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: scrape_amazon_dag.process_Interior_Accessories_3 manual__2025-04-04T22:06:59.454233+00:00 [queued]>
[2025-04-04T22:07:41.546+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 2
[2025-04-04T22:07:41.714+0000] {taskinstance.py:2889} INFO - Executing <Task(PythonOperator): process_Interior_Accessories_3> on 2025-04-04 22:06:59.454233+00:00
[2025-04-04T22:07:41.851+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'scrape_amazon_dag', 'process_Interior_Accessories_3', 'manual__2025-04-04T22:06:59.454233+00:00', '--job-id', '11', '--raw', '--subdir', 'DAGS_FOLDER/test_crawl_list_product.py', '--cfg-path', '/tmp/tmpk95em2s8']
[2025-04-04T22:07:41.820+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=2201) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-04-04T22:07:41.871+0000] {standard_task_runner.py:105} INFO - Job 11: Subtask process_Interior_Accessories_3
[2025-04-04T22:07:41.871+0000] {standard_task_runner.py:72} INFO - Started process 2254 to run task
[2025-04-04T22:07:49.114+0000] {task_command.py:467} INFO - Running <TaskInstance: scrape_amazon_dag.process_Interior_Accessories_3 manual__2025-04-04T22:06:59.454233+00:00 [running]> on host ba893f484bac
[2025-04-04T22:07:51.678+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='scrape_amazon_dag' AIRFLOW_CTX_TASK_ID='process_Interior_Accessories_3' AIRFLOW_CTX_EXECUTION_DATE='2025-04-04T22:06:59.454233+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-04-04T22:06:59.454233+00:00'
[2025-04-04T22:07:51.695+0000] {logging_mixin.py:190} INFO - Task instance is in running state
[2025-04-04T22:07:51.705+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2025-04-04T22:07:51.739+0000] {logging_mixin.py:190} INFO - Current task name:process_Interior_Accessories_3 state:running start_date:2025-04-04 22:07:41.419832+00:00
[2025-04-04T22:07:51.750+0000] {logging_mixin.py:190} INFO - Dag name:scrape_amazon_dag and current dag run status:running
[2025-04-04T22:07:51.760+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-04-04T22:07:51.762+0000] {test_crawl_list_product.py:227} INFO - Processing: Automotive/Interior Accessories - https://www.amazon.com/s?bbn=2562090011&rh=i%3Aspecialty-aps%2Cn%3A2562090011%2Cn%3A%2115690151%2Cn%3A15857501&s=date-desc-rank&ref_=nav_em__nav_desktop_sa_intl_interior_accessories_0_2_10_5
[2025-04-04T22:07:52.061+0000] {logger.py:11} INFO - ====== WebDriver manager ======
[2025-04-04T22:07:52.719+0000] {logger.py:11} INFO - Get LATEST chromedriver version for google-chrome
[2025-04-04T22:07:53.522+0000] {logger.py:11} INFO - About to download new driver from https://chromedriver.storage.googleapis.com/114.0.5735.90/chromedriver_linux64.zip
[2025-04-04T22:07:53.626+0000] {logger.py:11} INFO - Driver downloading response is 200
[2025-04-04T22:08:10.170+0000] {logger.py:11} INFO - Get LATEST chromedriver version for google-chrome
[2025-04-04T22:08:12.720+0000] {logger.py:11} INFO - Get LATEST chromedriver version for google-chrome
[2025-04-04T22:08:13.135+0000] {logger.py:11} INFO - Driver has been saved in cache [/home/***/.wdm/drivers/chromedriver/linux64/114.0.5735.90]
[2025-04-04T22:08:13.414+0000] {taskinstance.py:3311} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 417, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/test_crawl_list_product.py", line 228, in scrape_department
    scraper = AmazonScraper()
              ^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/test_crawl_list_product.py", line 41, in __init__
    self.setup_driver()
  File "/opt/airflow/dags/test_crawl_list_product.py", line 57, in setup_driver
    self.driver = webdriver.Chrome(service=service, options=chrome_options)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/selenium/webdriver/chrome/webdriver.py", line 45, in __init__
    super().__init__(
  File "/home/airflow/.local/lib/python3.12/site-packages/selenium/webdriver/chromium/webdriver.py", line 55, in __init__
    self.service.start()
  File "/home/airflow/.local/lib/python3.12/site-packages/selenium/webdriver/common/service.py", line 113, in start
    self.assert_process_still_running()
  File "/home/airflow/.local/lib/python3.12/site-packages/selenium/webdriver/common/service.py", line 126, in assert_process_still_running
    raise WebDriverException(f"Service {self._path} unexpectedly exited. Status code was: {return_code}")
selenium.common.exceptions.WebDriverException: Message: Service /home/airflow/.wdm/drivers/chromedriver/linux64/114.0.5735.90/chromedriver unexpectedly exited. Status code was: 127

[2025-04-04T22:08:13.612+0000] {logging_mixin.py:190} INFO - Task instance in failure state
[2025-04-04T22:08:13.693+0000] {logging_mixin.py:190} INFO - Task start:2025-04-04 22:07:41.419832+00:00 end:2025-04-04 22:08:13.610106+00:00 duration:32.190274
[2025-04-04T22:08:13.695+0000] {logging_mixin.py:190} INFO - Task:<Task(PythonOperator): process_Interior_Accessories_3> dag:<DAG: scrape_amazon_dag> dagrun:<DagRun scrape_amazon_dag @ 2025-04-04 22:06:59.454233+00:00: manual__2025-04-04T22:06:59.454233+00:00, state:running, queued_at: 2025-04-04 22:06:59.580718+00:00. externally triggered: True>
[2025-04-04T22:08:13.704+0000] {logging_mixin.py:190} INFO - Failure caused by Message: Service /home/***/.wdm/drivers/chromedriver/linux64/114.0.5735.90/chromedriver unexpectedly exited. Status code was: 127
[2025-04-04T22:08:13.709+0000] {taskinstance.py:1225} INFO - Marking task as UP_FOR_RETRY. dag_id=scrape_amazon_dag, task_id=process_Interior_Accessories_3, run_id=manual__2025-04-04T22:06:59.454233+00:00, execution_date=20250404T220659, start_date=20250404T220741, end_date=20250404T220813
[2025-04-04T22:08:14.036+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-04-04T22:08:14.072+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 11 for task process_Interior_Accessories_3 (Message: Service /home/airflow/.wdm/drivers/chromedriver/linux64/114.0.5735.90/chromedriver unexpectedly exited. Status code was: 127
; 2254)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/cli.py", line 116, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3005, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 273, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3159, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3183, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 417, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/test_crawl_list_product.py", line 228, in scrape_department
    scraper = AmazonScraper()
              ^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/test_crawl_list_product.py", line 41, in __init__
    self.setup_driver()
  File "/opt/airflow/dags/test_crawl_list_product.py", line 57, in setup_driver
    self.driver = webdriver.Chrome(service=service, options=chrome_options)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/selenium/webdriver/chrome/webdriver.py", line 45, in __init__
    super().__init__(
  File "/home/airflow/.local/lib/python3.12/site-packages/selenium/webdriver/chromium/webdriver.py", line 55, in __init__
    self.service.start()
  File "/home/airflow/.local/lib/python3.12/site-packages/selenium/webdriver/common/service.py", line 113, in start
    self.assert_process_still_running()
  File "/home/airflow/.local/lib/python3.12/site-packages/selenium/webdriver/common/service.py", line 126, in assert_process_still_running
    raise WebDriverException(f"Service {self._path} unexpectedly exited. Status code was: {return_code}")
selenium.common.exceptions.WebDriverException: Message: Service /home/airflow/.wdm/drivers/chromedriver/linux64/114.0.5735.90/chromedriver unexpectedly exited. Status code was: 127

[2025-04-04T22:08:14.409+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2025-04-04T22:08:14.510+0000] {taskinstance.py:3895} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-04-04T22:08:14.908+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
