[2025-04-08T03:39:33.442+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-04-08T03:39:34.506+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: scrape_amazon_dag.process_Oils___Fluids_6 manual__2025-04-08T03:39:12.456722+00:00 [queued]>
[2025-04-08T03:39:34.905+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: scrape_amazon_dag.process_Oils___Fluids_6 manual__2025-04-08T03:39:12.456722+00:00 [queued]>
[2025-04-08T03:39:34.910+0000] {taskinstance.py:2867} INFO - Starting attempt 1 of 2
[2025-04-08T03:39:39.512+0000] {taskinstance.py:2890} INFO - Executing <Task(PythonOperator): process_Oils___Fluids_6> on 2025-04-08 03:39:12.456722+00:00
[2025-04-08T03:39:39.538+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=5383) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-04-08T03:39:39.542+0000] {standard_task_runner.py:72} INFO - Started process 5439 to run task
[2025-04-08T03:39:39.565+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'scrape_amazon_dag', 'process_Oils___Fluids_6', 'manual__2025-04-08T03:39:12.456722+00:00', '--job-id', '153', '--raw', '--subdir', 'DAGS_FOLDER/test_crawl_list_product.py', '--cfg-path', '/tmp/tmp7r7bws7f']
[2025-04-08T03:39:39.591+0000] {standard_task_runner.py:105} INFO - Job 153: Subtask process_Oils___Fluids_6
[2025-04-08T03:39:41.313+0000] {task_command.py:467} INFO - Running <TaskInstance: scrape_amazon_dag.process_Oils___Fluids_6 manual__2025-04-08T03:39:12.456722+00:00 [running]> on host 13b4251b7529
[2025-04-08T03:39:41.941+0000] {taskinstance.py:3134} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='scrape_amazon_dag' AIRFLOW_CTX_TASK_ID='process_Oils___Fluids_6' AIRFLOW_CTX_EXECUTION_DATE='2025-04-08T03:39:12.456722+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-04-08T03:39:12.456722+00:00'
[2025-04-08T03:39:41.948+0000] {logging_mixin.py:190} INFO - Task instance is in running state
[2025-04-08T03:39:41.951+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2025-04-08T03:39:41.952+0000] {logging_mixin.py:190} INFO - Current task name:process_Oils___Fluids_6 state:running start_date:2025-04-08 03:39:34.507458+00:00
[2025-04-08T03:39:41.957+0000] {logging_mixin.py:190} INFO - Dag name:scrape_amazon_dag and current dag run status:running
[2025-04-08T03:39:41.958+0000] {taskinstance.py:732} INFO - ::endgroup::
[2025-04-08T03:39:41.970+0000] {taskinstance.py:3313} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 768, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 734, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 424, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: scrape_department() missing 1 required positional argument: 'user_agent'
[2025-04-08T03:39:41.998+0000] {logging_mixin.py:190} INFO - Task instance in failure state
[2025-04-08T03:39:41.999+0000] {logging_mixin.py:190} INFO - Task start:2025-04-08 03:39:34.507458+00:00 end:2025-04-08 03:39:41.997158+00:00 duration:7.4897
[2025-04-08T03:39:42.000+0000] {logging_mixin.py:190} INFO - Task:<Task(PythonOperator): process_Oils___Fluids_6> dag:<DAG: scrape_amazon_dag> dagrun:<DagRun scrape_amazon_dag @ 2025-04-08 03:39:12.456722+00:00: manual__2025-04-08T03:39:12.456722+00:00, state:running, queued_at: 2025-04-08 03:39:12.494777+00:00. externally triggered: True>
[2025-04-08T03:39:42.000+0000] {logging_mixin.py:190} INFO - Failure caused by scrape_department() missing 1 required positional argument: 'user_agent'
[2025-04-08T03:39:42.001+0000] {taskinstance.py:1226} INFO - Marking task as UP_FOR_RETRY. dag_id=scrape_amazon_dag, task_id=process_Oils___Fluids_6, run_id=manual__2025-04-08T03:39:12.456722+00:00, execution_date=20250408T033912, start_date=20250408T033934, end_date=20250408T033941
[2025-04-08T03:39:42.131+0000] {taskinstance.py:341} INFO - ::group::Post task execution logs
[2025-04-08T03:39:42.136+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 153 for task process_Oils___Fluids_6 (scrape_department() missing 1 required positional argument: 'user_agent'; 5439)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/cli.py", line 116, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3006, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 274, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3161, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3185, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 768, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 734, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 424, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: scrape_department() missing 1 required positional argument: 'user_agent'
[2025-04-08T03:39:42.223+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2025-04-08T03:39:42.281+0000] {taskinstance.py:3901} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-04-08T03:39:42.290+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
